services:
  - type: web
    name: cardapio2
    env: node
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    staticPublishPath: build 